import { Plus, Save, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useApp } from '../context/AppContext';
import { roleLabels } from '../lib/permissions';
import type { User, UserRole } from '../types';

const emptyUser: User = { uid: '', email: '', displayName: '', role: 'PERAWAT', unit: 'Hemodialisis' };

export function UsersPage() {
  const { user, dataMode } = useApp(); const [users, setUsers] = useState<User[]>([]); const [draft, setDraft] = useState<User>(emptyUser); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (dataMode !== 'firebase' || user?.role !== 'ADMIN') return; let unsubscribe: (() => void) | undefined; void import('../services/firebase').then(({ subscribeUserProfiles }) => { unsubscribe = subscribeUserProfiles(setUsers, setError); }); return () => unsubscribe?.(); }, [dataMode, user]);
  if (user?.role !== 'ADMIN') return <div className="notice danger">Halaman ini hanya dapat diakses Administrator.</div>;
  const save = async () => { if (!draft.uid.trim() || !draft.displayName.trim()) { setError('UID dan nama wajib diisi.'); return; } setSaving(true); setError(''); try { const { saveUserProfile } = await import('../services/firebase'); await saveUserProfile(draft); setDraft(emptyUser); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Profil gagal disimpan.'); } finally { setSaving(false); } };
  return <><header className="page-header"><div><span className="eyebrow">Firebase role management</span><h1>Pengguna dan akses</h1><p>Buat akun Email/Password di Firebase Authentication, lalu daftarkan UID dan role-nya di sini.</p></div><button className="button primary" onClick={() => setDraft(emptyUser)}><Plus /> Profil baru</button></header>{dataMode !== 'firebase' && <div className="notice warning">Masuk menggunakan akun Admin Firebase untuk mengelola profil.</div>}{error && <div className="notice danger">{error}</div>}<section className="user-admin-grid"><div className="panel"><div className="section-heading"><h2><Users /> Daftar profil</h2></div><div className="user-profile-list">{users.map((profile) => <button key={profile.uid} onClick={() => setDraft(profile)}><span><strong>{profile.displayName || 'Tanpa nama'}</strong><small>{profile.email || profile.uid}</small></span><b>{roleLabels[profile.role]}</b></button>)}</div></div><div className="panel"><div className="section-heading"><h2>{draft.uid ? 'Edit profil' : 'Profil baru'}</h2></div><label className="field"><span>Firebase Auth UID *</span><input value={draft.uid} disabled={users.some((item) => item.uid === draft.uid)} onChange={(e) => setDraft({ ...draft, uid: e.target.value })} /></label><label className="field"><span>Nama *</span><input value={draft.displayName} onChange={(e) => setDraft({ ...draft, displayName: e.target.value })} /></label><label className="field"><span>Email</span><input type="email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} /></label><label className="field"><span>Role</span><select value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value as UserRole })}>{(Object.keys(roleLabels) as UserRole[]).map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select></label><button className="button primary" disabled={saving || dataMode !== 'firebase'} onClick={save}><Save />{saving ? 'Menyimpan…' : 'Simpan profil'}</button></div></section></>;
}
